[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "scheduler-lambda"
version = "1.0.0"
description = 'Python project for lambda helper functions for scheduling compute resources in AWS'
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = ["dependencies"]

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]
 
[tool.hatch.build.targets.wheel.sources]
"src" = ""

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src tests}"

[tool.hatch.envs.default]
type = "virtual"
path = ".venv"
dependencies = [
  "pytest",
  "pytest-docker-tools",
  "pytest-unordered",
  "portpicker",
  "coverage[toml]>=6.5",
  "mypy>=1.0.0",
]

[tool.hatch.envs.default.scripts]
tests = "pytest {args:tests}"
checks = "mypy --install-types --non-interactive {args:src tests}"
cov-tests = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report",
]
cov = [
  "cov-tests",
  "cov-report",
]

[tool.hatch.envs.hatch-test]
default-args = ["tests"]
extra-args = ["-vv"]
parallel = true
extra-dependencies = [
  "pytest-docker-tools",
  "pytest-unordered",
  "portpicker",
]

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.12", "3.13", "3.14"]
version = ["latest"]

[tool.pytest.ini_options]
pythonpath = [
  "src",
]

[tool.coverage.run]
# source = ["src/"]
source_pkgs = ["scheduler_lambda", "tests"]
branch = true
parallel = true

[tool.coverage.paths]
scheduler_lambda = ["src", "*/scheduler-lambda/src"]
tests = ["tests", "*/scheduler-lambda/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
